openapi: 3.0.0
info:
  version: 2.1.0
  title: bk-chat
tags:
  - name: chat
    description: individual & group chat apis
servers:
  - url: https://dev-api.mygala.in
    description: dev
  - url: https://api.mygala.in
    description: prod
  - url: http://localhost:3000
    description: localhost
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  parameters:
    page:
      in: query
      name: page
      schema:
        type: number
    query:
      in: query
      name: q
      schema:
        type: string
      required: true
    weddingId:
      in: path
      description: unique id of the wedding
      name: weddingId
      schema:
        type: string
      required: true
    eventId:
      in: path
      description: unique id of the event
      name: eventId
      schema:
        type: string
      required: true
    id:
      in: path
      description: unique id
      name: id
      schema:
        type: string
      required: true
    userId:
      in: path
      description: the id can be email, username or phone
      name: userId
      schema:
        type: string
      required: true
    entity:
      in: path
      description: all, wedding, user etc; individual search components
      name: entity
      schema:
        type: string
      required: true
    qUserId:
      in: query
      description: the id of an user
      name: userId
      schema:
        type: string
      required: true
    streamId:
      in: path
      description: unique id of the video stream
      name: streamId
      schema:
        type: string
      required: true
    chatId:
      in: path
      description: unique id of a chat conversation
      name: chatId
      schema:
        type: string
      required: true
    app:
      in: query
      description: app from which the request is being sent
      name: app
      schema:
        type: string
        enum:
          - user
          - vendor
      required: true
    details:
      in: query
      description: if the full details is required or not
      name: details
      schema:
        type: boolean
        default: false
      required: true
    include:
      in: query
      description: extra includes based on requirement
      name: include
      schema:
        type: string
      required: false
    platform:
      in: header
      name: platform
      schema:
        type: string
        enum:
          - android
          - web
          - ios
      required: true
    appversion:
      in: header
      description: build number of the app
      name: appversion
      schema:
        type: integer
        default: 1
      required: true
    vendorId:
      in: path
      description: unique id of the vendor
      name: vendorId
      schema:
        type: integer
      required: true
    packageId:
      in: path
      description: unique id of a vendor package
      name: packageId
      schema:
        type: integer
      required: true
    locationId:
      in: path
      description: unique id of the location
      name: locationId
      schema:
        type: integer
      required: true
    commentId:
      in: path
      description: unique id of the comment
      name: commentId
      schema:
        type: integer
      required: true
    occasion:
      in: query
      name: occasion
      description: The occasion for which recommendations are requested.
      schema:
        type: string
        enum:
          - Birthday
          - Wedding
          - Engagement
          - HouseWarming
          - CorporateEvents
          - BabyShower
          - NamingCeremony
          - BachelorParty
          - Anniversary
      required: true
    wishlistId:
      in: path
      description: unique id of the wishlist
      name: wishlistId
      schema:
        type: string
      required: true
    parentId:
      in: query
      description: wishlist for requested parentId
      name: parentId
      schema:
        type: string
      required: true
  schemas:
    chat-message:
      properties:
        val:
          type: string
        at:
          type: number
        type:
          type: string
        users:
          type: array
          items:
            type: number
    update-chat:
      properties:
        isGroup:
          type: boolean
        users:
          type: array
          items:
            type: number
        name:
          type: string
        url:
          type: string
paths:
  /chat/v1/list:
    get:
      summary: >-
        to get list of individual & group chats which are in accepted or pending
        states
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      responses:
        '200':
          description: success
  /chat/v1/new:
    post:
      summary: to create an individual or group chat
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      responses:
        '200':
          description: success
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-chat'
  /chat/v1/{chatId}:
    get:
      summary: get chat users
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/chatId'
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      responses:
        '200':
          description: success
    put:
      summary: update chat users, name & url
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/chatId'
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      responses:
        '200':
          description: success
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update-chat'
  /chat/v1/{chatId}/accept:
    put:
      summary: to accept chat request
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
        - $ref: '#/components/parameters/chatId'
      responses:
        '200':
          description: success
  /chat/v1/{chatId}/exit:
    delete:
      summary: to exit & reject chat
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
        - $ref: '#/components/parameters/chatId'
        - $ref: '#/components/parameters/qUserId'
      responses:
        '200':
          description: success
  /chat/v1/{chatId}/admin:
    put:
      summary: make user as admin
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
        - $ref: '#/components/parameters/chatId'
        - $ref: '#/components/parameters/qUserId'
      responses:
        '200':
          description: success
    delete:
      summary: make user as non-admin
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
        - $ref: '#/components/parameters/chatId'
        - $ref: '#/components/parameters/qUserId'
      responses:
        '200':
          description: success
  /chat/v1/{chatId}/recent:
    put:
      summary: update recent chat message
      tags:
        - chat
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
        - $ref: '#/components/parameters/chatId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/chat-message'
      responses:
        '200':
          description: success
