openapi: 3.0.0
info:
  version: 1.0.0
  title: bk-general
tags:
  - name: general
    description: General public apis
servers:
  - url: https://dev-api.mygala.in
    description: dev
  - url: https://api.mygala.in
    description: prod
  - url: http://localhost:3000
    description: localhost
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  parameters:
    page:
      in: query
      name: page
      schema:
        type: number
    query:
      in: query
      name: q
      schema:
        type: string
      required: true
    entity:
      in: path
      description: all
      name: entity
      schema:
        type: string
      required: true
    app:
      in: query
      description: app from which the request is being sent
      name: app
      schema:
        type: string
        enum:
          - user
          - vendor
      required: true
    platform:
      in: header
      name: platform
      schema:
        type: string
        enum:
          - android
          - web
          - ios
      required: true
    appversion:
      in: header
      description: build number of the app
      name: appversion
      schema:
        type: integer
        default: 1
      required: true
  schemas:
    email:
      properties:
        email:
          type: string
    new-enquiry:
      properties:
        code:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        email:
          type: string
        location:
          type: string
        schedule:
          type: string
        services:
          type: array
          items:
            type: string
        price:
          type: string
        source:
          type: string
    default:
      type: object
paths:
  /general/v1/swagger:
    get:
      summary: gets the swagger config
      description: >-
        The swagger config api is not allowed on prod environment, it will work
        only on dev & stage environments. fetches & returns swagger config json
        from bk-utils
      tags:
        - general
      responses:
        '200':
          description: api successful
  /general/v1/config:
    get:
      summary: gets the app config
      tags:
        - general
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum:
              - web
              - app
              - vendor
          required: false
      responses:
        '200':
          description: api successful
  /general/v1/dial-codes:
    get:
      summary: get allowed country dial codes
      tags:
        - general
      responses:
        '200':
          description: api successful
  /general/v1/vendor-categories:
    get:
      summary: get allowed vendor categories
      tags:
        - general
      responses:
        '200':
          description: api successful
  /general/v1/search/{entity}:
    get:
      summary: global search; includes mini profiles, active invites, approved vendors
      tags:
        - general
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/entity'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      responses:
        '200':
          description: success
  /general/v1/enquiry:
    post:
      summary: create a new general enquiry
      tags:
        - general
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-enquiry'
      responses:
        '200':
          description: enquiry successfully created
  /general/v1/newsletter/new:
    put:
      summary: save email for newsletter
      tags:
        - general
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/email'
      responses:
        '200':
          description: email saved successfully
  /general/v1/feedback/new:
    post:
      summary: save new feedback
      tags:
        - general
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/default'
      responses:
        '200':
          description: feedback saved successfully
  /general/v1/report/new:
    post:
      summary: save new report
      tags:
        - general
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/default'
      responses:
        '200':
          description: success
