openapi: 3.0.0
info:
  version: 2.1.0
  title: bk-payment
tags:
  - name: payment
    description: post service apis
servers:
  - url: https://dev-api.mygala.in
    description: dev
  - url: https://api.mygala.in
    description: prod
  - url: http://localhost:3000
    description: localhost
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  parameters:
    platform:
      in: header
      name: platform
      schema:
        type: string
        enum:
          - android
          - web
          - ios
      required: true
    appversion:
      in: header
      description: build number of the app
      name: appversion
      schema:
        type: integer
        default: 1
      required: true
  schemas:
    new-account:
      required:
        - email
        - accountNumber
        - beneficiaryName
        - ifscCode
        - lat
        - lon
        - decode
      properties:
        email:
          type: string
          format: email
        accountNumber:
          type: string
        beneficiaryName:
          type: string
        ifscCode:
          type: string
        lat:
          type: number
        lon:
          type: number
        decode:
          type: boolean
    new-order:
      required:
        - name
        - parentId
        - side
        - amount
        - currency
        - anonymous
        - message
      properties:
        name:
          type: string
        parentId:
          type: string
        side:
          type: string
        amount:
          type: string
        currency:
          type: string
        anonymous:
          type: boolean
        message:
          type: string
    new-order-app:
      required:
        - parentId
        - side
        - amount
        - currency
        - anonymous
        - message
      properties:
        parentId:
          type: string
        side:
          type: string
        amount:
          type: string
        currency:
          type: string
        anonymous:
          type: boolean
        message:
          type: string
paths:
  /payment/v1/accounts/new:
    post:
      summary: create linked account for user
      tags:
        - payment
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-account'
      responses:
        '200':
          description: success
  /payment/v1/orders/new:
    post:
      summary: create a new payment order
      tags:
        - payment
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-order'
      responses:
        '200':
          description: success
  /payment/v1/orders/new/app:
    post:
      summary: create a new payment order
      tags:
        - payment
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-order-app'
      responses:
        '200':
          description: success