openapi: 3.0.0
info:
  version: 1.0.0
  title: bk-asset
tags:
  - name: asset
    description: asset service apis
servers:
  - url: https://dev-api.mygala.in
    description: dev
  - url: https://api.mygala.in
    description: prod
  - url: http://localhost:3000
    description: localhost
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  parameters:
    platform:
      in: header
      name: platform
      schema:
        type: string
        enum:
          - android
          - web
          - ios
      required: true
    appversion:
      in: header
      description: build number of the app
      name: appversion
      schema:
        type: integer
        default: 1
      required: true
  schemas:
    new-asset:
      properties:
        url:
          type: string
        parentId:
          type: string
        resource:
          type: string
        assetType:
          type: string
        meta:
          type: object
paths:
  /asset/v1/new:
    post:
      summary: create new asset & return signed url
      tags:
        - asset
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-asset'
      responses:
        '200':
          description: success
  /asset/v1/{assetId}:
    delete:
      summary: delete asset by id
      tags:
        - asset
      security:
        - Bearer: []
      parameters:
        - in: path
          name: assetId
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      responses:
        '200':
          description: success
    get:
      summary: get asset by id
      tags:
        - asset
      security:
        - Bearer: []
      parameters:
        - in: path
          name: assetId
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      responses:
        '200':
          description: success
    put:
      summary: update asset by id
      tags:
        - asset
      security:
        - Bearer: []
      parameters:
        - in: path
          name: assetId
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/parameters/appversion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-asset'
      responses:
        '200':
          description: success
